title: Fangyuan (Milar) Liu                                # your name (or website title) here
logo: "Profile.JPG"                                        # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS in Business Analytics Candidate, 2020
  Simon Business School, 
  University of Rochester
  <br><br>
  <a href="https://www.linkedin.com/in/fangyuanmilarliu/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/milarliu/milarliu.github.io/">View My Projects on GitHub</a>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


