title: Fangyuan (Milar) Liu                                                               # your name (or website title) here
logo: "file:///Users/fangyuan.liu/Desktop/Photos/IMG_4427.JPG?raw=true"                   # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS in Business Analytics Candidate 2020
  at Simon Business School, University of Rochester
  <br><br>
  Life Adventurer 
  <br><br>
  <a href="www.linkedin.com/in/fangyuanmilarliu">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


